import express from "express";
import cors from "cors";
import helmet from "helmet";
import cookieParser from "cookie-parser";
import rateLimit from "express-rate-limit";
import bcrypt from "bcryptjs";
import "dotenv/config";
import { db, transaction } from "./db.js";
import { clearSession, issueSession, requireAdmin, requireAuth } from "./auth.js";

const app = express();
app.use(helmet({ crossOriginResourcePolicy: false }));
app.use(cors({ origin: process.env.FRONTEND_ORIGIN || "http://localhost:3000", credentials: true }));
app.use(express.json({ limit: "1mb" }));
app.use(cookieParser());
const loginLimit = rateLimit({ windowMs: 10*60*1000, limit: 20, standardHeaders: true, legacyHeaders: false });
const initials = (name) => name.split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase();

app.get("/api/health", async (_req,res,next)=>{ try { await db.query("SELECT 1"); res.json({ok:true,database:"mysql"}); } catch(e){next(e);} });
app.post("/api/auth/login", loginLimit, async (req,res,next)=>{ try {
  const [rows] = await db.execute("SELECT * FROM users WHERE email=? AND active=1 LIMIT 1", [String(req.body.email||"").trim().toLowerCase()]);
  const user=rows[0]; if(!user || !(await bcrypt.compare(String(req.body.password||""),user.password_hash))) return res.status(401).json({error:"Email or password is incorrect"});
  await db.execute("UPDATE users SET last_login_at=NOW() WHERE id=?",[user.id]); issueSession(res,user);
  res.json({user:{id:user.id,name:user.name,email:user.email,role:user.global_role}});
} catch(e){next(e);} });
app.post("/api/auth/logout",(_req,res)=>{clearSession(res);res.json({ok:true});});
app.get("/api/auth/me",requireAuth,async(req,res,next)=>{try{const [r]=await db.execute("SELECT id,name,email,global_role role FROM users WHERE id=? AND active=1",[req.auth.id]);if(!r[0])return res.status(401).json({error:"Session expired"});res.json({user:r[0]});}catch(e){next(e);}});
app.use("/api",requireAuth);

app.get("/api/projects",async(req,res,next)=>{try{const sql=req.auth.role==='super_admin'?"SELECT project_key `key`,name,description,color,status FROM projects ORDER BY created_at":"SELECT p.project_key `key`,p.name,p.description,p.color,p.status FROM projects p JOIN project_members pm ON pm.project_id=p.id WHERE pm.user_id=? ORDER BY p.created_at";const [rows]=await db.execute(sql,req.auth.role==='super_admin'?[]:[req.auth.id]);res.json({projects:rows});}catch(e){next(e);}});
app.post("/api/projects",requireAdmin,async(req,res,next)=>{try{const name=String(req.body.name||"").trim(),key=String(req.body.key||"").trim().toUpperCase().replace(/[^A-Z0-9]/g,"");if(name.length<3||key.length<2||key.length>8)return res.status(400).json({error:"Valid project name and 2-8 character key required"});const [result]=await db.execute("INSERT INTO projects(project_key,name,description,color,created_by) VALUES(?,?,?,?,?)",[key,name,String(req.body.description||""),req.body.color||"#6052d7",req.auth.id]);await db.execute("INSERT INTO project_members(project_id,user_id,role) VALUES(?,?,'project_manager')",[result.insertId,req.auth.id]);res.status(201).json({project:{key,name,description:String(req.body.description||""),color:req.body.color||"#6052d7",status:"active"}});}catch(e){if(e.code==='ER_DUP_ENTRY')return res.status(409).json({error:"Project key already exists"});next(e);}});

app.get("/api/tickets",async(req,res,next)=>{try{const key=String(req.query.project||"");const [tickets]=await db.execute(`SELECT t.ticket_key id,t.title,t.type,t.priority,t.status,COALESCE(u.name,'Unassigned') assigneeName,t.due_date dueDate,COALESCE(l.name,'General') label FROM tickets t JOIN projects p ON p.id=t.project_id LEFT JOIN users u ON u.id=t.assignee_id LEFT JOIN ticket_labels tl ON tl.ticket_id=t.id LEFT JOIN labels l ON l.id=tl.label_id WHERE p.project_key=? AND t.deleted_at IS NULL ORDER BY t.updated_at DESC`,[key]);const [activities]=await db.execute(`SELECT a.id,t.ticket_key ticketId,IF(a.action='comment','comment',IF(a.action='status','status','created')) kind,u.name authorName,COALESCE(a.comment,'') body,a.old_value fromStatus,a.new_value toStatus,a.created_at createdAt FROM activity_logs a JOIN tickets t ON t.id=a.ticket_id JOIN projects p ON p.id=t.project_id JOIN users u ON u.id=a.user_id WHERE p.project_key=? UNION ALL SELECT c.id+1000000,t.ticket_key,'comment',u.name,c.body,NULL,NULL,c.created_at FROM comments c JOIN tickets t ON t.id=c.ticket_id JOIN projects p ON p.id=t.project_id JOIN users u ON u.id=c.user_id WHERE p.project_key=? ORDER BY createdAt DESC`,[key,key]);res.json({tickets:tickets.map(t=>({...t,assignee:initials(t.assigneeName),dueDate:t.dueDate?new Date(t.dueDate).toISOString().slice(0,10):null})),activities});}catch(e){next(e);}});
app.post("/api/tickets",async(req,res,next)=>{try{const title=String(req.body.title||"").trim(),key=String(req.body.projectKey||"");if(!title)return res.status(400).json({error:"Title is required"});const ticket=await transaction(async(c)=>{const [ps]=await c.execute("SELECT id,next_ticket_number FROM projects WHERE project_key=? FOR UPDATE",[key]);if(!ps[0])throw Object.assign(new Error("Project not found"),{status:404});const p=ps[0],ticketKey=`${key}-${p.next_ticket_number}`;const [users]=await c.query("SELECT id FROM users WHERE active=1 ORDER BY id LIMIT 1");const [r]=await c.execute("INSERT INTO tickets(project_id,ticket_number,ticket_key,title,description,type,priority,status,assignee_id,reporter_id) VALUES(?,?,?,?,?,?,?,'To Do',?,?)",[p.id,p.next_ticket_number,ticketKey,title,String(req.body.description||""),req.body.type||"Task",req.body.priority||"Medium",users[0]?.id||null,req.auth.id]);await c.execute("UPDATE projects SET next_ticket_number=next_ticket_number+1 WHERE id=?",[p.id]);await c.execute("INSERT INTO activity_logs(ticket_id,user_id,action,comment) VALUES(?,?,'created','Ticket created')",[r.insertId,req.auth.id]);return{id:ticketKey};});res.status(201).json({ticket});}catch(e){next(e);}});
app.patch("/api/tickets",async(req,res,next)=>{try{const id=String(req.body.id||""),status=String(req.body.status||"");if(!["To Do","In Progress","In Review","Done"].includes(status))return res.status(400).json({error:"Invalid status"});await transaction(async(c)=>{const [rows]=await c.execute("SELECT id,status,assignee_id FROM tickets WHERE ticket_key=? AND deleted_at IS NULL FOR UPDATE",[id]);if(!rows[0])throw Object.assign(new Error("Ticket not found"),{status:404});await c.execute("UPDATE tickets SET status=? WHERE id=?",[status,rows[0].id]);await c.execute("INSERT INTO activity_logs(ticket_id,user_id,action,field_name,old_value,new_value,comment) VALUES(?,?,'status','status',?,?,?)",[rows[0].id,req.auth.id,rows[0].status,status,String(req.body.comment||"")]);if(rows[0].assignee_id&&rows[0].assignee_id!==req.auth.id)await c.execute("INSERT INTO notifications(user_id,type,ticket_id,title,body) VALUES(?,'status',?,?,?)",[rows[0].assignee_id,rows[0].id,`${id} moved to ${status}`,String(req.body.comment||"Status updated")]);});res.json({ok:true});}catch(e){next(e);}});
app.post("/api/comments",async(req,res,next)=>{try{const body=String(req.body.body||"").trim();if(!body)return res.status(400).json({error:"Comment is required"});const [t]=await db.execute("SELECT id FROM tickets WHERE ticket_key=? AND deleted_at IS NULL",[req.body.ticketId]);if(!t[0])return res.status(404).json({error:"Ticket not found"});const [r]=await db.execute("INSERT INTO comments(ticket_id,user_id,body) VALUES(?,?,?)",[t[0].id,req.auth.id,body]);res.status(201).json({comment:{id:r.insertId}});}catch(e){next(e);}});
app.get("/api/users",requireAdmin,async(_req,res,next)=>{try{const [users]=await db.query("SELECT id,name,email,global_role role,active,last_login_at lastLoginAt FROM users ORDER BY name");res.json({users});}catch(e){next(e);}});
app.post("/api/users",requireAdmin,async(req,res,next)=>{try{const name=String(req.body.name||"").trim(),email=String(req.body.email||"").trim().toLowerCase(),password=String(req.body.password||"");if(name.length<2||!email.includes('@')||password.length<8)return res.status(400).json({error:"Name, valid email and 8+ character password required"});const hash=await bcrypt.hash(password,12);const [r]=await db.execute("INSERT INTO users(name,email,password_hash,global_role) VALUES(?,?,?,?)",[name,email,hash,req.body.role==='super_admin'?'super_admin':'user']);res.status(201).json({user:{id:r.insertId,name,email}});}catch(e){if(e.code==='ER_DUP_ENTRY')return res.status(409).json({error:"Email already exists"});next(e);}});
app.patch("/api/users/:id",requireAdmin,async(req,res,next)=>{try{await db.execute("UPDATE users SET global_role=?,active=? WHERE id=?",[req.body.role==='super_admin'?'super_admin':'user',req.body.active?1:0,Number(req.params.id)]);res.json({ok:true});}catch(e){next(e);}});
app.get("/api/settings",requireAdmin,async(_req,res,next)=>{try{const [r]=await db.execute("SELECT setting_value settings FROM app_settings WHERE setting_key='workspace'");res.json({settings:r[0]?.settings||{}});}catch(e){next(e);}});
app.patch("/api/settings",requireAdmin,async(req,res,next)=>{try{const value={workspaceName:String(req.body.workspaceName||"TaskFlow").slice(0,80),allowInvites:Boolean(req.body.allowInvites),emailNotifications:Boolean(req.body.emailNotifications),defaultView:["Board","List","Reports"].includes(req.body.defaultView)?req.body.defaultView:"Board"};await db.execute("INSERT INTO app_settings(setting_key,setting_value,updated_by) VALUES('workspace',?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value),updated_by=VALUES(updated_by)",[JSON.stringify(value),req.auth.id]);res.json({settings:value});}catch(e){next(e);}});
app.get("/api/notifications",async(req,res,next)=>{try{const [rows]=await db.execute("SELECT id,title,body,read_at readAt,created_at createdAt FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 50",[req.auth.id]);res.json({notifications:rows});}catch(e){next(e);}});

app.use((err,_req,res,_next)=>{console.error(err);res.status(err.status||500).json({error:err.status?err.message:"Server error"});});
const port=Number(process.env.API_PORT||4000);app.listen(port,()=>console.log(`Jirra MySQL API http://localhost:${port}`));
