CREATE DATABASE IF NOT EXISTS jirra CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE jirra;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  global_role ENUM('super_admin','manager','user') NOT NULL DEFAULT 'user',
  avatar_color CHAR(7) NOT NULL DEFAULT '#6052d7',
  active BOOLEAN NOT NULL DEFAULT TRUE,
  last_login_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_users_active (active)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS teams (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  description VARCHAR(500) NOT NULL DEFAULT '',
  created_by BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_teams_creator FOREIGN KEY (created_by) REFERENCES users(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS team_members (
  team_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (team_id,user_id),
  CONSTRAINT fk_tm_team FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE,
  CONSTRAINT fk_tm_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS projects (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  project_key VARCHAR(8) NOT NULL UNIQUE,
  name VARCHAR(120) NOT NULL,
  description VARCHAR(1000) NOT NULL DEFAULT '',
  color CHAR(7) NOT NULL DEFAULT '#6052d7',
  status ENUM('active','archived') NOT NULL DEFAULT 'active',
  next_ticket_number INT UNSIGNED NOT NULL DEFAULT 1,
  created_by BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_projects_creator FOREIGN KEY (created_by) REFERENCES users(id),
  INDEX idx_projects_status (status)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS project_members (
  project_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  role ENUM('project_manager','member','viewer') NOT NULL DEFAULT 'member',
  via_team_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (project_id,user_id),
  CONSTRAINT fk_pm_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
  CONSTRAINT fk_pm_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_pm_team FOREIGN KEY (via_team_id) REFERENCES teams(id) ON DELETE SET NULL,
  INDEX idx_pm_user (user_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS tickets (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  project_id BIGINT UNSIGNED NOT NULL,
  ticket_number INT UNSIGNED NOT NULL,
  ticket_key VARCHAR(24) NOT NULL UNIQUE,
  title VARCHAR(180) NOT NULL,
  description TEXT NOT NULL,
  type ENUM('Task','Bug','Feature','Improvement') NOT NULL DEFAULT 'Task',
  priority ENUM('Low','Medium','High','Urgent') NOT NULL DEFAULT 'Medium',
  status ENUM('To Do','In Progress','In Review','Done') NOT NULL DEFAULT 'To Do',
  assignee_id BIGINT UNSIGNED NULL,
  reporter_id BIGINT UNSIGNED NOT NULL,
  due_date DATE NULL,
  deleted_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_t_project FOREIGN KEY (project_id) REFERENCES projects(id),
  CONSTRAINT fk_t_assignee FOREIGN KEY (assignee_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_t_reporter FOREIGN KEY (reporter_id) REFERENCES users(id),
  UNIQUE KEY uq_ticket_project_number (project_id,ticket_number),
  INDEX idx_tickets_project_status (project_id,status,deleted_at),
  INDEX idx_tickets_assignee (assignee_id,deleted_at),
  INDEX idx_tickets_updated (updated_at)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS labels (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, project_id BIGINT UNSIGNED NOT NULL, name VARCHAR(60) NOT NULL, color CHAR(7) NOT NULL DEFAULT '#777777', UNIQUE KEY uq_label(project_id,name), CONSTRAINT fk_label_project FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS ticket_labels (ticket_id BIGINT UNSIGNED NOT NULL,label_id BIGINT UNSIGNED NOT NULL,PRIMARY KEY(ticket_id,label_id),CONSTRAINT fk_tl_ticket FOREIGN KEY(ticket_id) REFERENCES tickets(id) ON DELETE CASCADE,CONSTRAINT fk_tl_label FOREIGN KEY(label_id) REFERENCES labels(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS comments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,ticket_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,body TEXT NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NULL,CONSTRAINT fk_comment_ticket FOREIGN KEY(ticket_id) REFERENCES tickets(id) ON DELETE CASCADE,CONSTRAINT fk_comment_user FOREIGN KEY(user_id) REFERENCES users(id),INDEX idx_comments_ticket(ticket_id,created_at)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS activity_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,ticket_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,action VARCHAR(40) NOT NULL,field_name VARCHAR(60) NULL,old_value TEXT NULL,new_value TEXT NULL,comment TEXT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT fk_activity_ticket FOREIGN KEY(ticket_id) REFERENCES tickets(id) ON DELETE CASCADE,CONSTRAINT fk_activity_user FOREIGN KEY(user_id) REFERENCES users(id),INDEX idx_activity_ticket(ticket_id,created_at)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS attachments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,ticket_id BIGINT UNSIGNED NOT NULL,original_name VARCHAR(255) NOT NULL,stored_name VARCHAR(255) NOT NULL,mime_type VARCHAR(120) NOT NULL,size_bytes BIGINT UNSIGNED NOT NULL,uploaded_by BIGINT UNSIGNED NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT fk_attach_ticket FOREIGN KEY(ticket_id) REFERENCES tickets(id) ON DELETE CASCADE,CONSTRAINT fk_attach_user FOREIGN KEY(uploaded_by) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS notifications (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,type VARCHAR(40) NOT NULL,ticket_id BIGINT UNSIGNED NULL,title VARCHAR(180) NOT NULL,body VARCHAR(500) NOT NULL,read_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT fk_notif_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,CONSTRAINT fk_notif_ticket FOREIGN KEY(ticket_id) REFERENCES tickets(id) ON DELETE CASCADE,INDEX idx_notifications_user(user_id,read_at,created_at)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS app_settings (setting_key VARCHAR(100) PRIMARY KEY,setting_value JSON NOT NULL,updated_by BIGINT UNSIGNED NOT NULL,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,CONSTRAINT fk_settings_user FOREIGN KEY(updated_by) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS refresh_tokens (id CHAR(36) PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,token_hash CHAR(64) NOT NULL UNIQUE,expires_at DATETIME NOT NULL,revoked_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT fk_refresh_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,INDEX idx_refresh_expiry(expires_at)) ENGINE=InnoDB;
